# Generated by Django 4.0.4 on 2022-05-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(max_length=100)),
                ('bebida', models.CharField(max_length=100)),
                ('NomeRestaurante', models.ManyToManyField(to='pizzaria.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('NomeCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='pizzaria.cliente')),
                ('NomeMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='pizzaria.menu')),
            ],
        ),
    ]
