# Generated by Django 4.0.4 on 2022-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='name',
            new_name='comidas',
        ),
    ]
